* Intro
This project is a work in progress, but the goal is to make a hanging vplotter robot that is completely self contained and is controlled by the esp32.

Currently, there is support for controlling a DC motor and reading a quadrature encoder. In addition I have developed a websockets based debug interface that displays variables and allows the user to adjust them from the browser in real time.



* TODO:
- Finish supporting 2 motors/encoders
- Design and build physical frame/wheels of the robot.
- integrate esp portion and webInterface portion
- Clean up the debug page and make it nicer
  - Such as having the graph choose different colors for each variable [DONE]
  - Tickmarks for both axis
  - autoscale

* Ideas: (AKA notes to self)
  PID loop (keep motors at specified location)
  Something that takes in a path and generates points to feed to PID loop
  Path generation (maybe 2 parts) (given gcode, output stuff to ...


  position control (PID, motor control)
  motion planing (generate points for ^, controls velocity, acceleration, etc.)
  path planning (decides path robot will take to draw given
  path generation (from images, patterns, spirography, [[https://www.youtube.com/watch?v=_5So027H_fM][Lissajous]])


* Notes
  Make sure espfs is on v0.9.0. The most recent versions change how the 'espFsOpen' function is called.
