* Intro
This project is a work in progress, but the goal is to make a hanging vplotter robot that is completely self contained and is controlled by the esp32. It uses 2 DC motors with encoders instead of the usual stepper motors.

I'm currently in the process of starting over again, this time using the Arduino framework since my goal is to make something that is easy for other people to use. (You can still checkout the previous version on its own branch.) Currently, I have remade a web debug interface using websockets that makes it easy to view, graph, and modify variables from a browser. I also was able to figure out how to read the encoders and update the motors from an ISR, and I'll be working on adding documentation about that shortly on hackaday.io. Eventually, I plan on splitting these parts of the code out into their own libraries since I think they could be useful for other people.


* Websockets debug
  https://hackaday.io/project/164975-portable-vertical-plotter/log/191201-websockets-debug




* This is built standing on the shoulders of these projects:
  - https://github.com/me-no-dev/AsyncTCP (esp32 webserver base)
  - https://github.com/me-no-dev/ESPAsyncWebServer (esp32 webserver with websockets)
  - https://picnicss.com/ (css styling for webpage)
  - https://github.com/leeoniya/uPlot/ (js plotting library)
